#define FLOW_TAP_TERM 60
#define CHORDAL_HOLD
#undef TAPPING_TERM
#define TAPPING_TERM 250

#define PERMISSIVE_HOLD

#define USB_SUSPEND_WAKEUP_DELAY 0
#define CAPS_LOCK_STATUS
#define SERIAL_NUMBER "rdXPn/bvnLbp"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60

#define CHORDAL_HOLD

#define CAPS_WORD_INVERT_ON_SHIFT

#define VOYAGER_USER_LEDS

#define CAPS_WORD_IDLE_TIMEOUT 0
